const express = require('express');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const archiver = require('archiver');
const os = require('os');

const app = express();
app.use(express.json({ limit: '10mb' }));

const LOCKED_PKG = 'buildmeamod';
const FABRIC_API_VERSION = '0.92.2+1.20.1';
const MC_VERSION = '1.20.1';

// ── Health check ──
app.get('/', (req, res) => res.json({ status: 'ok', service: 'minecraft-mod-builder' }));

// ── Main build endpoint ──
app.post('/build', async (req, res) => {
  const { projectId, modName, generated_files } = req.body;

  if (!generated_files || !modName) {
    return res.status(400).json({ error: 'Missing modName or generated_files' });
  }

  const modId = modName.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), `mod-${modId}-`));

  try {
    console.log(`[BUILD] Starting build for: ${modId} (project: ${projectId})`);

    // ── 1. יצירת מבנה תיקיות ──
    const srcDir = path.join(tmpDir, 'src/main/java/com', LOCKED_PKG);
    const resDir = path.join(tmpDir, 'src/main/resources');
    
    fs.mkdirSync(path.join(srcDir, 'registry'), { recursive: true });
    fs.mkdirSync(path.join(srcDir, 'item'), { recursive: true });
    fs.mkdirSync(path.join(srcDir, 'block'), { recursive: true });
    fs.mkdirSync(path.join(srcDir, 'entity'), { recursive: true });
    fs.mkdirSync(path.join(resDir, `assets/${modId}/models/item`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `assets/${modId}/models/block`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `assets/${modId}/blockstates`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `assets/${modId}/lang`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `assets/${modId}/textures/item`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `assets/${modId}/textures/block`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `data/${modId}/recipes`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `data/${modId}/loot_tables/blocks`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `data/${modId}/loot_tables/entities`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `data/${modId}/worldgen/configured_feature`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `data/${modId}/worldgen/placed_feature`), { recursive: true });
    fs.mkdirSync(path.join(resDir, `data/minecraft/tags/worldgen/biome`), { recursive: true });

    const gf = generated_files;

    // ── 2. כתיבת קבצי Java ──
    const javaFiles = {
      'Main.java': gf.Main,
      'registry/ModItems.java': gf.ModItems,
      'registry/ModBlocks.java': gf.ModBlocks,
      'registry/ModEntities.java': gf.ModEntities,
      'item/TacticalCarbineItem.java': gf.TacticalCarbineItem,
      'item/ModMaterialItem.java': gf.ModMaterialItem,
      'block/ModOreBlock.java': gf.ModOreBlock,
    };

    // entity class
    const entityKey = gf._entity_class_key;
    if (entityKey && gf[entityKey]) {
      javaFiles[`entity/${entityKey}.java`] = gf[entityKey];
    }

    for (const [file, content] of Object.entries(javaFiles)) {
      if (content) {
        fs.writeFileSync(path.join(srcDir, file), content, 'utf8');
      }
    }

    // ── 3. fabric.mod.json ──
    const fabricModJson = {
      schemaVersion: 1,
      id: modId,
      version: '1.0.0',
      name: modName,
      description: `${modName} mod generated by MindrentAI`,
      authors: ['MindrentAI'],
      contact: {},
      license: 'MIT',
      environment: '*',
      entrypoints: { main: [`com.${LOCKED_PKG}.Main`] },
      mixins: [],
      depends: {
        fabricloader: '>=0.14.0',
        fabric: '*',
        minecraft: `~${MC_VERSION}`,
        java: '>=17'
      }
    };
    fs.writeFileSync(path.join(resDir, 'fabric.mod.json'), JSON.stringify(fabricModJson, null, 2));

    // ── 4. assets ──
    if (gf.LanguageJson) {
      fs.writeFileSync(path.join(resDir, `assets/${modId}/lang/en_us.json`), gf.LanguageJson);
    }

    // Item models
    if (gf.ItemModelJson) {
      try {
        const itemModels = JSON.parse(gf.ItemModelJson);
        for (const [name, model] of Object.entries(itemModels)) {
          if (!name.includes('/')) {
            fs.writeFileSync(
              path.join(resDir, `assets/${modId}/models/item/${name}.json`),
              JSON.stringify(model, null, 2)
            );
          }
        }
      } catch(e) { console.warn('ItemModelJson parse failed:', e.message); }
    }

    // Block models
    if (gf.BlockModelJson) {
      try {
        const blockModels = JSON.parse(gf.BlockModelJson);
        for (const [name, model] of Object.entries(blockModels)) {
          fs.writeFileSync(
            path.join(resDir, `assets/${modId}/models/block/${name}.json`),
            JSON.stringify(model, null, 2)
          );
        }
      } catch(e) { console.warn('BlockModelJson parse failed:', e.message); }
    }

    // Blockstates
    if (gf.BlockStateJson) {
      try {
        const blockStates = JSON.parse(gf.BlockStateJson);
        for (const [name, state] of Object.entries(blockStates)) {
          fs.writeFileSync(
            path.join(resDir, `assets/${modId}/blockstates/${name}.json`),
            JSON.stringify(state, null, 2)
          );
        }
      } catch(e) { console.warn('BlockStateJson parse failed:', e.message); }
    }

    // ── 5. data files ──
    if (gf.RecipeJson) {
      fs.writeFileSync(path.join(resDir, `data/${modId}/recipes/main.json`), gf.RecipeJson);
    }
    if (gf.LootTableJson) {
      const oreBlock = gf._registry_blocks?.split(',')[0] || 'ore_block';
      fs.writeFileSync(path.join(resDir, `data/${modId}/loot_tables/blocks/${oreBlock}.json`), gf.LootTableJson);
    }
    if (gf.BlockLootTableJson) {
      fs.writeFileSync(path.join(resDir, `data/${modId}/loot_tables/blocks/storage_block.json`), gf.BlockLootTableJson);
    }
    if (gf.OreFeatureJson) {
      const oreBlock = gf._registry_blocks?.split(',')[0] || 'ore_block';
      fs.writeFileSync(path.join(resDir, `data/${modId}/worldgen/configured_feature/${oreBlock}.json`), gf.OreFeatureJson);
    }
    if (gf.OrePlacementJson) {
      const oreBlock = gf._registry_blocks?.split(',')[0] || 'ore_block';
      fs.writeFileSync(path.join(resDir, `data/${modId}/worldgen/placed_feature/${oreBlock}.json`), gf.OrePlacementJson);
    }

    // extra data files
    if (gf._extra_data_files) {
      try {
        const extraDataFiles = typeof gf._extra_data_files === 'string'
          ? JSON.parse(gf._extra_data_files)
          : gf._extra_data_files;
        for (const [filePath, content] of Object.entries(extraDataFiles)) {
          const fullPath = path.join(resDir, filePath);
          fs.mkdirSync(path.dirname(fullPath), { recursive: true });
          fs.writeFileSync(fullPath, JSON.stringify(content, null, 2));
        }
      } catch(e) { console.warn('extra_data_files failed:', e.message); }
    }

    // ── 6. build.gradle ──
    const buildGradle = `
plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
    id 'maven-publish'
}

version = '1.0.0'
group = 'com.${LOCKED_PKG}'

base { archivesName = '${modId}' }

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${MC_VERSION}"
    mappings "net.fabricmc:yarn:${MC_VERSION}+build.10:v2"
    modImplementation "net.fabricmc:fabric-loader:0.15.6"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${FABRIC_API_VERSION}"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}
`;
    fs.writeFileSync(path.join(tmpDir, 'build.gradle'), buildGradle);

    // settings.gradle
    fs.writeFileSync(path.join(tmpDir, 'settings.gradle'), `rootProject.name = '${modId}'`);

    // gradle.properties
    fs.writeFileSync(path.join(tmpDir, 'gradle.properties'), `
org.gradle.jvmargs=-Xmx2G
minecraft_version=${MC_VERSION}
loader_version=0.15.6
fabric_version=${FABRIC_API_VERSION}
`);

    // ── 7. קומפילציה עם Gradle ──
    console.log(`[BUILD] Running gradle build in ${tmpDir}`);
    
    execSync('gradle build --no-daemon -x test', {
      cwd: tmpDir,
      timeout: 120000,
      stdio: 'pipe',
      env: { ...process.env, JAVA_HOME: process.env.JAVA_HOME || '/usr/lib/jvm/java-17-openjdk-amd64' }
    });

    // ── 8. מציאת ה-JAR שנבנה ──
    const libsDir = path.join(tmpDir, 'build/libs');
    const jarFiles = fs.readdirSync(libsDir).filter(f => f.endsWith('.jar') && !f.includes('sources'));
    
    if (jarFiles.length === 0) throw new Error('No JAR file found after build');

    const jarPath = path.join(libsDir, jarFiles[0]);
    const jarBuffer = fs.readFileSync(jarPath);
    const jarBase64 = jarBuffer.toString('base64');
    const sizeKb = Math.round(jarBuffer.length / 1024);

    console.log(`[BUILD] Success! JAR: ${jarFiles[0]} (${sizeKb} KB)`);

    return res.json({
      success: true,
      file_name: `${modId}-1.0.0.jar`,
      jar_base64: jarBase64,
      size_kb: sizeKb.toString(),
      file_count: Object.keys(gf).filter(k => !k.startsWith('_')).length,
      manifest: {
        sourceFiles: Object.keys(javaFiles).filter(k => gf[k.split('/').pop().replace('.java','')]).length,
        items: (gf._registry_items || '').split(',').filter(Boolean),
        blocks: (gf._registry_blocks || '').split(',').filter(Boolean),
        dataPackFiles: 3,
      },
      logs: [`Build successful: ${modId}-1.0.0.jar (${sizeKb} KB)`]
    });

  } catch (error) {
    console.error('[BUILD ERROR]', error.message);
    return res.status(500).json({
      success: false,
      error: error.message,
      logs: [`Build failed: ${error.message}`]
    });
  } finally {
    // ניקוי תיקייה זמנית
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Minecraft Mod Builder listening on port ${PORT}`));
